import * as Rpc from "effect/unstable/rpc/Rpc";
import {
  WorkspaceOverviewPayload,
  WorkspaceOverviewResult,
  CreateHarnessSessionPayload,
  CreateHarnessSessionResult,
  GetHarnessLibraryPayload,
  GetHarnessLibraryResult,
  GetHarnessSkillsPayload,
  GetHarnessSkillsResult,
  HarnessConfigurationError,
  ImportScienceHarnessPayload,
  RemoveHarnessProjectPayload,
  SaveHarnessPayload,
  SaveHarnessProjectPayload,
  ChatHarnessPayload,
  GetChatHarnessResult,
  ListHarnessRunsResult,
  GetHarnessRunPayload,
  GetHarnessRunResult,
  ListWorkflowRunsResult,
  GetWorkflowRunPayload,
  GetWorkflowRunResult,
  UpdateHarnessViewPayload,
  HarnessResourcePayload,
  HarnessResourceResult,
  ToolCredentialPayload,
  ToolCredentialResult,
  SaveToolCredentialPayload,
  HarnessMemoryPayload,
  HarnessMemoryResult,
  ListCurationPayload,
  ListCurationResult,
  DecideCurationPayload,
  DecideCurationResult,
  RollbackCurationPayload,
  RunCuratorReviewPayload,
  RunCuratorReviewResult,
  ListInstructionVersionsPayload,
  ListInstructionVersionsResult,
  ReadInstructionVersionPayload,
  ReadInstructionVersionResult,
} from "@supernova/contracts/harnesses/procedures";

export const HarnessRpcs = [
  Rpc.make("getWorkspaceOverview", {payload: WorkspaceOverviewPayload, success: WorkspaceOverviewResult, error: HarnessConfigurationError}),
  Rpc.make("getHarnessResources", {payload: HarnessResourcePayload, success: HarnessResourceResult, error: HarnessConfigurationError}),
  Rpc.make("getToolCredentials", {payload: ToolCredentialPayload, success: ToolCredentialResult, error: HarnessConfigurationError}),
  Rpc.make("saveToolCredential", {payload: SaveToolCredentialPayload, success: ToolCredentialResult, error: HarnessConfigurationError}),
  Rpc.make("getHarnessMemory", {payload: HarnessMemoryPayload, success: HarnessMemoryResult, error: HarnessConfigurationError}),
  Rpc.make("updateHarnessView", {payload: UpdateHarnessViewPayload, success: GetHarnessLibraryResult, error: HarnessConfigurationError}),
  Rpc.make("getChatHarness", {payload: ChatHarnessPayload, success: GetChatHarnessResult, error: HarnessConfigurationError}),
  Rpc.make("listHarnessRuns", {payload: ChatHarnessPayload, success: ListHarnessRunsResult, error: HarnessConfigurationError}),
  Rpc.make("getHarnessRun", {payload: GetHarnessRunPayload, success: GetHarnessRunResult, error: HarnessConfigurationError}),
  Rpc.make("listWorkflowRuns", {payload: ChatHarnessPayload, success: ListWorkflowRunsResult, error: HarnessConfigurationError}),
  Rpc.make("getWorkflowRun", {payload: GetWorkflowRunPayload, success: GetWorkflowRunResult, error: HarnessConfigurationError}),
  Rpc.make("getHarnessLibrary", {payload: GetHarnessLibraryPayload, success: GetHarnessLibraryResult, error: HarnessConfigurationError}),
  Rpc.make("getHarnessSkills", {payload: GetHarnessSkillsPayload, success: GetHarnessSkillsResult, error: HarnessConfigurationError}),
  Rpc.make("saveHarness", {payload: SaveHarnessPayload, success: GetHarnessLibraryResult, error: HarnessConfigurationError}),
  Rpc.make("saveHarnessProject", {payload: SaveHarnessProjectPayload, success: GetHarnessLibraryResult, error: HarnessConfigurationError}),
  Rpc.make("removeHarnessProject", {payload: RemoveHarnessProjectPayload, success: GetHarnessLibraryResult, error: HarnessConfigurationError}),
  Rpc.make("importScienceHarness", {payload: ImportScienceHarnessPayload, success: GetHarnessLibraryResult, error: HarnessConfigurationError}),
  Rpc.make("createHarnessSession", {payload: CreateHarnessSessionPayload, success: CreateHarnessSessionResult, error: HarnessConfigurationError}),
  Rpc.make("listCuration", {payload: ListCurationPayload, success: ListCurationResult, error: HarnessConfigurationError}),
  Rpc.make("decideCuration", {payload: DecideCurationPayload, success: DecideCurationResult, error: HarnessConfigurationError}),
  Rpc.make("rollbackCuration", {payload: RollbackCurationPayload, success: DecideCurationResult, error: HarnessConfigurationError}),
  Rpc.make("runCuratorReview", {payload: RunCuratorReviewPayload, success: RunCuratorReviewResult, error: HarnessConfigurationError}),
  Rpc.make("listInstructionVersions", {payload: ListInstructionVersionsPayload, success: ListInstructionVersionsResult, error: HarnessConfigurationError}),
  Rpc.make("readInstructionVersion", {payload: ReadInstructionVersionPayload, success: ReadInstructionVersionResult, error: HarnessConfigurationError}),
] as const;
