export const DESKTOP_IPC_CHANNELS = {
  openDirectory: "desktop:open-directory",
  setNativeTheme: "desktop:set-native-theme",
  showWorkspaceBrowser: "desktop:workspace-browser-show",
  hideWorkspaceBrowser: "desktop:workspace-browser-hide",
  navigateWorkspaceBrowser: "desktop:workspace-browser-navigate",
  goBackWorkspaceBrowser: "desktop:workspace-browser-back",
  goForwardWorkspaceBrowser: "desktop:workspace-browser-forward",
  reloadWorkspaceBrowser: "desktop:workspace-browser-reload",
  getUpdateState: "desktop:get-update-state",
  checkForUpdates: "desktop:check-for-updates",
  downloadUpdate: "desktop:download-update",
  installUpdate: "desktop:install-update",
  updateState: "desktop:update-state",
} as const;
